/**
 * New node file
 */

	rapid.define({
		"config.rapid-service-sockjs":{
			prefix:"/haha/heihei"
		},
		// httpserver只做为一个文件server,没有其它内容
		"config.rapid-httpserver":{
			autoStart:true,
			loading_dir:["/src"],
			defaultAction:function(){
				var req = this.request;
				this.emit("error",new Error("can not handle this request [" + req.url + "]"));
				return;
			},
			filter:[
		         {
		        	 doFilter:'whatFilter'
		         },
		         {
		        	 doFilter:'whoFilter'
		         },
		         {
		        	 doFilter:'howFilter'
		         },
		         {
		        	 doFilter:"addHeaders",
		        	 params:{
		        		 "x-send-by-setHeader" : "rapidjs"
		        	 }
		         }
	         ],
			mapping:[
				{
					url:"/",
					resource:"/app/index.html"
				},
	           {
					url:"/sync_error",
					doAction:function(){
						throw new Error("what is this?");
					}
				},
				{
					url:"/async_error",
					doAction:function(){
						setTimeout(function(){
							throw new Error("what is this?");
						},200)
					}
				},
				{
					url:"/nullaction",
					doAction:"nullaction"
				},
				{
					url:"/echo",
					doAction:"simpleEcho"
				},
				{
					url:"/sayhello",
					doAction:"sayHello",
					params:{name:"wangsu"}
				},
				{
					url:"/forward",
					doAction:"forwardImg"
				},
				{
					url:"/redirect",
					doAction:"redirectTo"
				},
				{
					url:"/get_img",
					doAction:"sendImg"
				},
				{
					url:"/testcookie",
					doAction:"testcookie"
				},
				{
					url:"/removecookie",
					doAction:"removecookie"
				},
				{
					url:"/replace_error",
					doAction:"replace_error"
				},
				{
					url:"/getTestList",
					doAction:"getList"
				},
		        {
					url:"/favicon.ico",
		        	http_status:{
		        		code:404
		        	}
		        },
			    {
			    	url:"/*",
			    	resource:"/app/*",
			    	params:{
			    		gzip:true
			    	}
	    		}
			]
		}
	});